export interface Agent {
  ID: string;
  Name: string;
  Title: string;
  Position: string;
  Type: string;
  Race: string;
  Gender: string;
  CharAtkType_1: number;
  CharAtkType_2: number;
  CharAtkType_3: number;
  CharAtkType_4: number;
  CharAtkType_5: number;
  CharAtkType_6: number;
  CharAtkType_7: number;
  sk1icon: string;
  sk12con: string;
  sk13con: string;
  sk1context: string;
  sk2context: string;
  sk3context: string;
  sk1: string;
  sk2: string;
  sk3: string;
  sk1cool: string;
  sk2cool: string;
  sk3cool: string;
  spinever: string;
}
